// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQNMOR6Om7eQZWq9NtPhcyWEXwlX3SUs',
    appId: '1:961018403699:web:28c72aa31bebc273354306',
    messagingSenderId: '961018403699',
    projectId: 'savebills-3eef7',
    authDomain: 'savebills-3eef7.firebaseapp.com',
    storageBucket: 'savebills-3eef7.appspot.com',
    measurementId: 'G-ZHGWEWK9G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZ2-GYawdNusv2lVVNkImVYHDlCPFxqU',
    appId: '1:961018403699:android:bd8b20cf1f887812354306',
    messagingSenderId: '961018403699',
    projectId: 'savebills-3eef7',
    storageBucket: 'savebills-3eef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD293u93XZMMwfPOaCwulD5K2-IpByL-kc',
    appId: '1:961018403699:ios:a6aa6ff22e0cdbc1354306',
    messagingSenderId: '961018403699',
    projectId: 'savebills-3eef7',
    storageBucket: 'savebills-3eef7.appspot.com',
    iosClientId: '961018403699-drh1roa17rrd8fitt09ataee6hbi47m2.apps.googleusercontent.com',
    iosBundleId: 'com.a5starcompany.savebills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD293u93XZMMwfPOaCwulD5K2-IpByL-kc',
    appId: '1:961018403699:ios:a6aa6ff22e0cdbc1354306',
    messagingSenderId: '961018403699',
    projectId: 'savebills-3eef7',
    storageBucket: 'savebills-3eef7.appspot.com',
    iosClientId: '961018403699-drh1roa17rrd8fitt09ataee6hbi47m2.apps.googleusercontent.com',
    iosBundleId: 'com.a5starcompany.savebills',
  );
}
